name: C:\Users\Chinmay\satTrack\satTrackAPI\venv
channels:
  - conda-forge
  - defaults
dependencies:
  - boost-cpp=1.72.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.4.5.1
  - cartopy=0.18.0
  - cffi=1.14.0
  - cfitsio=3.470
  - chardet=3.0.4
  - curl=7.69.1
  - cycler=0.10.0
  - expat=2.2.9
  - freetype=2.10.2
  - freexl=1.0.5
  - gdal=3.1.0
  - geos=3.8.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - glib=2.64.3
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icc_rt=2019.0.0
  - icu=64.2
  - idna=2.9
  - intel-openmp=2020.0
  - jpeg=9c
  - kealib=1.4.13
  - krb5=1.17.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.69.1
  - libffi=3.2.1
  - libgdal=3.1.0
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.7.4
  - libpng=1.6.37
  - libpq=12.2
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - matplotlib-base=3.2.1
  - mkl=2020.0
  - msys2-conda-epoch=20160418
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1g
  - owslib=0.19.2
  - pcre=8.44
  - pip=20.0.2
  - poppler=0.88.0
  - poppler-data=0.4.9
  - postgresql=12.2
  - proj=7.0.0
  - pycparser=2.20
  - pyepsg=0.4.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyshp=2.1.0
  - pysocks=1.7.1
  - python=3.8.3
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pyyaml=5.3.1
  - requests=2.23.0
  - scipy=1.3.2
  - setuptools=46.4.0
  - shapely=1.7.0
  - six=1.15.0
  - sqlite=3.31.1
  - tbb=2020.1
  - tiledb=2.0.3
  - tk=8.6.10
  - tornado=6.0.4
  - urllib3=1.25.9
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.34.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xerces-c=3.2.2
  - xz=5.2.5
  - yaml=0.2.4
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - arrow==0.15.5
    - bleach==3.1.4
    - certifi==2019.11.28
    - click==7.1.1
    - cryptography==2.8
    - flask==1.1.1
    - itsdangerous==1.1.0
    - jinja2==2.11.1
    - jplephem==2.14
    - kiwisolver==1.1.0
    - markupsafe==1.1.1
    - mpld3==0.3
    - numpy==1.18.2
    - pillow==7.0.0
    - python-dotenv==0.13.0
    - sgp4==2.12
    - skyfield==1.21
    - werkzeug==1.0.0

